### PR TITLE
Allow read/writes with buffers > sector_size

### PR DESCRIPTION
**Pull request by reynir**
While the current solo5 implementation only allows I/O operations of exactly one block (sector) we don't necessarily have to expose this in the Mirage interface.

We internally split the buffers into sector_size large sub buffers when performing reads and writes.

### CODE REVIEW

**Comment by hannesm** [comment]
hmm, so consider we have a sector size of 2048 bytes, and now a write is performed with a heterogeneous list of 2047; 2049; 2048 buffers, what should the result be?

before this PR, an error would be raised
after this PR (if I understand it correctly), if we start writing at sector 0: 0 -> 2047 bytes; 1 -> 2048 bytes; 2 -> 1 byte; 3 -> 2048 bytes

is this the desired behaviour?

I guess one way would be to concat the cstruct.t and split them into sector_size... but then I also think the old behaviour is rather straightforward, and we recently adapted some KV implementations (e.g. tar) to cope with this...

**Comment by reynir** [comment]
Hmm, no, the behavior is slightly different, but you have a point. We rely on the tender to return an error if the buffer is not aligned with the sector_size. In your example it would fail at the first write because it would split the first buffer into 2047, 0 byte buffers, and a 2047 byte buffer write would fail.
But a write  with 2049 and 2048 buffers would result in trying to write: 2048, 1, 2048 byte buffers. The first write would succeed but the next would fail. That is, we partially wrote the first (original) buffer, and didn't write the second buffer. This may not be what we want. As far as I read the documentation for mirage-block it allows partial writes.

```OCaml
 (* [write device sector_start buffers] writes data from [buffers]                                        
    onto the block device starting at [sector_start]. [Ok ()] means                                       
    the contents of the buffers have been written. [Error _]                                              
    indicates a partial failure in which some of the writes may not                                       
    have happened. *)
```

Before this PR we could request a write with buffers of length 2048, 1 bytes, and it would write the first buffer and then fail on the second.

**Comment by reynir** [comment]
For Xen it requires that all buffers are exactly one page / 4096 bytes, and fails early if any of the buffers is not.

https://github.com/mirage/mirage-block-xen/blob/main/lib/front/blkfront.ml#L461

**Comment by reynir** [comment]
For Unix the buffers are checked to be sector aligned before read and write operations: https://github.com/mirage/mirage-block-unix/blob/main/lib/block.ml#L256-L264

**Comment by reynir** [comment]
With #29 these concerns should be gone.

**Comment by reynir** [comment]
Rebased on top of #29.

**Comment by hannesm** [comment]
Could you rebase onto main (since #29 was merged, the diff here looks like it still includes the #29 changes)?

**Comment by reynir** [comment]
Done

**Comment by hannesm** [comment]
Thanks

**Pull request merged**
